name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: test
    runs-on: ubuntu-latest

    services:
        postgres:
            image: postgres:12
            env:
                POSTGRES_USER: root
                POSTGRES_PASSWORD: secret
                POSTGRES_DB: simpleback
            options: >-
                --health-cmd pg_isready
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5


    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install Go golang-migrate
      run: |
       curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.darwin-amd64.tar.gz | tar xvz
       sudo mv migrate /usr/bin/ 
       which migrate

    - name: Run migration
      run: make migrateup


    - name: Test
      run: make test